version: '3.8'

services:
  app:
    container_name: app-expo
    build: ./front
    ports:
      - "9000:9000"
    volumes:
      - ./front:/app
      - /app/node_modules 
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge