version: '3.8'

services:
  back:
    container_name: app_back
    build: ./back
    ports:
      - "9002:80"
    volumes:
      - ./back:/usr/src/agendaBella
    networks:
      - app_network
  database:
    container_name: app_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agendaBella
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app_network
  #front:
  #  build:
  #    context: ./front
  #    dockerfile: Dockerfile
  #  ports:
  #    - "9001:8081"       # Web
  #    - "19000:19000"     # Expo dev
  #    - "19001:19001"     # Metro bundler websocket
  #    - "19002:19002"     # Expo dev tools (browser)
  #  volumes:
  #    - ./front:/agendaBella
  #  networks:
  #    - app-network
 
networks:
  app_network:
    driver: bridge